sql-3: As a developer I want to have login and registration routes
BinaryStudioAcademy/bsa-2023-squirrel pull request #15
Opened 2023-08-22 09:32 UTC by OlegKarapysh

added jwt authentication

2023-08-22 12:41 UTC, Anatolii-Ivanov requested changes

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.BLL/Services/AuthService.cs
> +        var token = await GenerateNewAccessToken(userId, username, userLoginDto.Email);
No need to assign variable
Just return await ...

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.BLL/Services/AuthService.cs
> +        var token = await GenerateNewAccessToken(userId, username, userLoginDto.Email);
Everywhere

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.BLL/Services/AuthService.cs
> +        if (userRegisterDto.Password != userRegisterDto.ConfirmPassword)
This check should be on frontend, we won't send it to FE

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.Common/JWT/AccessToken.cs
> +    public int ExpiresIn { get; }
This part is stored in token itself, so no need to send additional data (Which are valid only for millisecond)

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.Common/Squirrel.Core.Common.csproj
> +    </Reference>
What is it:)

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/SampleController.cs
> +    [Authorize] // For authentication tests.
You don't need to commit this line :)

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/AuthController.cs
> +    /// /// /// <remarks>
I guess you don't need so many / here) The same with previous one

2023-08-22 12:41 UTC, Anatolii-Ivanov commented on backend/Squirrel.Core/Squirrel.Core.Common/JWT/JwtFactory.cs
> +    }
This is done by ASP.NET Core itself, are you sure we need this?

2023-08-22 15:42 UTC, Anatolii-Ivanov approved these changes, later dismissed

2023-08-23 08:46 UTC, VladTkach submitted a review, later dismissed

2023-08-23 09:09 UTC, VladTkach approved these changes, later dismissed

2023-08-23 09:37 UTC, Anatolii-Ivanov approved these changes

2023-08-23 09:43 UTC, VladTkach approved these changes

2023-08-23 09:43 UTC, merged