sql-47: Add Text service
BinaryStudioAcademy/bsa-2023-squirrel pull request #25
Opened 2023-08-23 18:05 UTC by serhiiyasenev

2023-08-24 20:57 UTC, Anatolii-Ivanov approved these changes, later dismissed

2023-08-24 21:43 UTC, alinaSielina requested changes

2023-08-24 21:43 UTC, alinaSielina commented on backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/TextController.cs
> +public sealed class TextController : ControllerBase
Currently, we don't need this controller.

2023-08-25 07:31 UTC, serhiiyasenev commented on backend/Squirrel.Core/Squirrel.Core.WebAPI/Controllers/TextController.cs
> +public sealed class TextController : ControllerBase
deleted

2023-08-25 08:37 UTC, alinaSielina approved these changes

2023-08-25 08:37 UTC, merged