sql-30: As a user I want to have console app
BinaryStudioAcademy/bsa-2023-squirrel pull request #3
Opened 2023-08-21 09:30 UTC by serhiiyasenev

2023-08-21 16:23 UTC, alinaSielina requested changes
The ConsoleApp should be a separate project and should not be a part of Squirrel.Core. The structure should be as follows:
- Squirrel.Core
- Squirrel.Notifier
- Squirrel.ConsoleApp

2023-08-21 17:24 UTC, serhiiyasenev commented
Updated - ConsoleApp as a separate project

2023-08-21 18:54 UTC, alinaSielina approved these changes

2023-08-22 09:48 UTC, OlegKarapysh approved these changes

2023-08-22 10:43 UTC, merged