31: added headers to main page
BinaryStudioAcademy/bsa-2023-squirrel pull request #31
Opened 2023-08-24 21:26 UTC by anastasiianosulich

2023-08-24 21:41 UTC, Anatolii-Ivanov requested changes
This one is better, just some small comments :)

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/.eslintrc
Please, don't change these files

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/.vscode/settings.json
Please, don't change these files

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/angular.json
Please, don't change these files

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/package-lock.json
Remove it, please (from commit)

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/main/main-page/headers/main-header/main-header.component.sass
> +    border-bottom: 1px solid #e8e6e6
Colors to vars

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/main/main-page/headers/navbar-header/navbar-header.component.html
> +            </li>
Can you make it as a list of items, which we will load from ts file?

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/main/main-page/headers/navbar-header/navbar-header.component.sass
> +  padding: 1rem 0
Let's not use rem, please, px, %, vh, vw

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/main/main-routing.module.ts
> +            },
Why you need this one?

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/dropdown/dropdown.component.sass
> +$arrow-color: #8e8c8c
Move to global vars (maybe we have it)

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/dropdown/dropdown.component.sass
> +
Enters

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/index.html
> +</head>
tabulation

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/yarn.lock
Drop from git

2023-08-24 21:41 UTC, Anatolii-Ivanov commented on frontend/src/styles/global.sass
> +$primary-violet: #503AF9
We have separate file for colors

2023-08-27 19:34 UTC, OlegKarapysh commented on frontend/src/app/modules/main/main-page/headers/main-header/main-header.component.ts
> +    onDatabaseSelected(value: string) {
it's better to use explicit access modifiers (public, private...) as we do in C#

2023-08-27 19:34 UTC, OlegKarapysh commented on frontend/src/app/modules/main/main-page/headers/main-header/main-header.component.ts
> +    }
why do you use ngOnInit here?

2023-08-28 12:16 UTC, anastasiianosulich commented
Screenshot of the component.

![Знімок екрана 2023-08-28 151456](https://github.com/BinaryStudioAcademy/bsa-2023-squirrel/assets/84079192/dba7a40c-d2f4-47d5-b4c3-b648a3f69031)

2023-08-28 12:21 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/main/main-page/headers/navbar-header/navbar-header.component.html
> +                }}</a>
```suggestion
                <a routerLink="{{ navLink.path }}" routerLinkActive="active" class="navbar-link">
                    {{ navLink.displayName }}
                </a>
```

2023-08-29 11:29 UTC, OlegKarapysh commented
resolve merge conflicts as quickly as possible because they reset received approvals

2023-08-29 11:36 UTC, OlegKarapysh commented on frontend/src/app/shared/components/dropdown/dropdown.component.ts
> +}
missing access modifiers here

2023-08-30 13:08 UTC, Anatolii-Ivanov approved these changes

2023-08-30 13:50 UTC, VladTkach approved these changes

2023-08-30 14:10 UTC, OlegKarapysh approved these changes

2023-08-30 14:11 UTC, merged