51: As a user I want to have PRs page content
BinaryStudioAcademy/bsa-2023-squirrel pull request #41
Opened 2023-08-28 00:02 UTC by Zoranais

**PR page:**
![pr page](https://i.imgur.com/68D8Y2b.png)
**Input:** 
![input](https://i.imgur.com/QhWJ2DV.png)
**Auto-complete:**
![auto-complete](https://i.imgur.com/Rpx1Emh.png)
**Low resolution:**
![low resolution](https://i.imgur.com/C0tADFc.png)

2023-08-28 09:49 UTC, Anatolii-Ivanov requested changes

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/core/services/time-span-stringifier.service.ts
> +    }
Can you check moment library, it should have string comparison mechanism

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.html
> +            </app-dropdown-select>
Can you make items to be shown inside dropdown, not on top/left of it

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.html
> +                <p>{{ item.firstName + ' ' + item.lastName }} {{ item.userName ? '(' + item.userName + ')' : '' }}</p>
Move to ts and just load value / execute function

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.sass
> +    margin-left: 0px !important
Are you sure, importatnt is needed here?

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.ts
> +    }
```suggestion
    filterUsers(item: any, value: string) {
        const lowerValue = value.toLowerCase();
        const fullName = `${item.firstName} ${item.lastName}`;
        
        return fullName.toLowerCase().indexOf(lowerValue) >= 0
        || item.userName.toLowerCase().indexOf(lowerValue) >= 0
        || item.email.indexOf(lowerValue) >= 0;

    }
```

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request-list/pull-request-list.component.ts
> +    }
And it will be better to move it to some helper class, can be reused later

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request/pull-request.component.html
> +                    {{ calculateTime(pullRequest.updatedAt) }} ago
Move to ts

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/pull-request/pull-request/pull-request.component.ts
> +        } as PullRequest;
Move to function/onInit

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
> +     * */
Remove these comments, and as I understand, unused variables

2023-08-28 09:49 UTC, Anatolii-Ivanov commented on frontend/src/app/shared/components/dropdown-select/dropdown-select.component.ts
> +    }
And this one is not really needed

2023-08-28 12:58 UTC, Zoranais commented
**Page**
![1](https://i.imgur.com/MQV2Voj.png)
**Page with selected filters**
![2](https://i.imgur.com/LfFNNV6.png)
**Page with selected filters and low resolution**
![3](https://i.imgur.com/ioxZ2vJ.png)

2023-08-28 13:14 UTC, VladTkach reviewed
![image](https://github.com/BinaryStudioAcademy/bsa-2023-squirrel/assets/70843124/dd71aaa5-7506-4deb-ad14-7e66d21ee278)
This arrow is too small.
And also drop-down list for branch, isn't it better to remove the other options when ALL is chosen?

2023-08-28 14:26 UTC, Zoranais commented
The arrow size was increased, now selecting the placeholder option will remove all others, and selecting the non-placeholder option will remove the placeholder one.
![1](https://i.imgur.com/DsKEgzF.png)

2023-08-28 17:41 UTC, Anatolii-Ivanov approved these changes

2023-08-29 09:12 UTC, VladTkach approved these changes

2023-08-29 09:19 UTC, merged