72: created project card component according to design
BinaryStudioAcademy/bsa-2023-squirrel pull request #66
Opened 2023-09-03 08:54 UTC by nazar-kotyuha

![image](https://github.com/BinaryStudioAcademy/bsa-2023-squirrel/assets/93193343/67d231eb-d9e2-4861-87fc-bb7bd4cc93b6)

2023-09-03 09:10 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +    <div class="project-date">12-12-2024</div>
Can you also move these fields to ts file model?

2023-09-03 09:11 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/projects/project-card/project-card.component.ts
> +        this.accentColor = this.project.engine === 'PostgreSQL' ? '#FF6532' : '#e79925';
Move these colors to const in file

2023-09-03 09:54 UTC, Zoranais requested changes

2023-09-03 09:54 UTC, Zoranais commented on frontend/src/app/modules/projects/project-card/project-card.component.sass
> +    color: #282828
Please use $text-main from color.sass here.

2023-09-03 09:54 UTC, Zoranais commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +        </ng-template>
"/assets/postgresql.svg" will be enough. Also, it's better to implement a method in ts to get the image path for the current DbEngine, no need for ng-template here.

2023-09-03 09:54 UTC, Zoranais commented on frontend/src/assets/sqlserver.png
Please use svg format for icons. Also in our design a different logo is defined for it.

2023-09-03 09:54 UTC, Zoranais commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +        </div>
It will be better to add padding to its content.

2023-09-03 09:54 UTC, Zoranais commented on frontend/src/app/modules/projects/project-card/project-card.component.sass
> +    font-size: 12px
```suggestion
.engine-tag
    min-width: 33px
    width: fit-content
    border-radius: 10px
    border: 0.75px $accentColor solid
    text-align: center
    color: $accentColor
    font-size: 12px
    font-weight: 500
```

2023-09-04 10:22 UTC, Zoranais submitted a review, later dismissed
All suggested changes were implemented.

2023-09-04 10:51 UTC, Anatolii-Ivanov approved these changes, later dismissed

2023-09-04 11:26 UTC, Anatolii-Ivanov approved these changes, later dismissed

2023-09-04 11:54 UTC, alinaSielina commented on frontend/src/app/modules/projects/project-card/project-card.component.ts
> +    public sampleDate: string = '12-12-2024';
please move the date and the description to the projectDto  class as fields

2023-09-04 15:43 UTC, alinaSielina commented on frontend/src/app/modules/projects/project-card/project-card.component.ts
> +    private postgresSqlAccentColor: string = '#FF6532';
I think you can use a single [ngClass] binding instead of a separate accentColor property, for example:

```
[ngClass]="{
  'postgreSql': project.engine === DbEngines.PostgreSql,
  'sqlServer': project.engine === DbEngines.SqlServer
}
```

2023-09-04 15:43 UTC, alinaSielina commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +            {{ project.engine }}
it is a project tag, not a project engine

2023-09-05 06:38 UTC, alinaSielina commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +            {{ project.engine }}
If a project has tags, they will be displayed here
![image](https://github.com/BinaryStudioAcademy/bsa-2023-squirrel/assets/139565128/e5fd80e5-ada6-4991-9407-20f44b209fbf)

2023-09-05 06:38 UTC, alinaSielina commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +    <div class="project-date">{{ project.date | formatDate }}</div>
Maybe can we use [DatePipe](https://angular.io/api/common/DatePipe)?

2023-09-05 06:38 UTC, alinaSielina commented on frontend/src/app/modules/projects/project-card/project-card.component.html
> +        sqlServer: project.engine === 'SqlServer'
looks good, but maybe we can use DbEngine enum?

2023-09-05 20:01 UTC, closed without merging